# Generated by Django 6.0.2 on 2026-05-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpools', '0001_initial'),
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideoffer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_offers', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='drop_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_requests', to='network.node'),
        ),
    ]
