# Generated by Django 6.0.2 on 2026-05-23 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpools', '0002_initial'),
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='network.node'),
        ),
        migrations.AddField(
            model_name='rideoffer',
            name='ride_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_offers', to='carpools.riderequest'),
        ),
    ]
