# Generated by Django 6.0.2 on 2026-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wallet_balance_alter_user_role_driverprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('PASSENGER', 'Passenger')], default='', max_length=50),
        ),
    ]
