# Generated by Django 6.0.2 on 2026-05-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_number',
        ),
    ]
