# Generated by Django 6.0.2 on 2026-05-22 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('route', models.JSONField(blank=True, default=list)),
                ('visited_nodes', models.JSONField(blank=True, default=list)),
                ('max_passengers', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_current', to='network.node')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_end', to='network.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_start', to='network.node')),
            ],
        ),
    ]
